### ISSUE TITLE
A small critic on the license

### ISSUE THREAD

**Issue by thelinuxlich** [differentialhq/differential#39]
In 2024 it's not hard to create a E2E system with Node, TS and some client-side fetch. Elysia and Hono, the newest frameworks, already support this use case. I think your monetization approach by giving the open source project a viral license is flawed, as it will just make people look the integrations you did with background queues and other extra batteries and they will do it by hand on the newer frameworks.

**Comment by nadeesha** [comment]
Thanks for your thoughts @thelinuxlich.

> In 2024 it's not hard to create a E2E system with Node, TS and some client-side fetch. Elysia and Hono, the newest frameworks, already support this use case

Yes, it's not hard. But it could be easier. Elysia, Hono, tRPC, gRPC they all solve service to service communication for specific frameworks and runtimes (such as Bun). 

But Differential is different because it works like a service bus where services connect to a central control-plane, that orchestrates job distribution. It's not working on a client/server paradigm, but a many-to-many services interoperability.

> I think your monetization approach by giving the open source project a viral license is flawed

That's not at all the monetisation approach for this project. In fact, you can self-host the project and pay us nothing (self-hosting guide is incoming). I respect your right to think calling GPLv3 a viral license, but I don't think that has any implications on our monetisation strategy.

We definitely don't want the IP being used to create commercially competitive work that is not open-source. And we don't want to be as restrictive as [fair code](https://faircode.io/) licenses. 

I want to tread carefully here. It's easy to go from a less-permissive license to a more permissive one, and in all honesty we will consider that in the future. But the reverse would be in poor form.

Thank you for your thoughtful criticism. If I can expand on anything above, please let me know.

**Comment by thelinuxlich** [comment]
It's not my opinion, it's a fact. If I distribute a service using GPL3 code I need to open source everything else under GPL3 too(this hijacking even other open source licenses that could be already in place, like BSD)

**Comment by thelinuxlich** [comment]
Also, any lawyer specialized in open source licenses will tell you to avoid code in GPL3/AGPL3 at all costs. I don't have any skin in this game, but I think you are setting artificial obstacles to external collaboration by not picking a license without the viral aspect.

**Comment by nadeesha** [comment]
Your concerns on the perception of using the GPLv3 is valid. There are those with a [contrary view](https://en.wikipedia.org/wiki/Viral_license#:~:text=Richard%20Stallman%20has%20described%20this%20view%20with%20an%20analogy%2C%20saying%2C%20%22The%20GPL%27s%20domain%20does%20not%20spread%20by%20proximity%20or%20contact%2C%20only%20by%20deliberate%20inclusion%20of%20GPL%2Dcovered%20code%20in%20your%20program.%20It%20spreads%20like%20a%20spider%20plant%2C%20not%20like%20a%20virus.) as well.

We will revisit the issue of the license in the near future. Thank you.

**Comment by nadeesha** [comment]
@thelinuxlich Thanks for the feedback. We're changing the license to Apache 2.0 :)
